version: '3.9'

services:
  influxdb:
    image: influxdb:2.0.6-alpine
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: bravo
      DOCKER_INFLUXDB_INIT_PASSWORD: bravo
      DOCKER_INFLUXDB_INIT_ORG: bravo
      DOCKER_INFLUXDB_INIT_BUCKET: bravo
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: bravo
    ports:
      - 8086:8086
    networks:
      - monitoring_availibility_network

#  telegraf:
#    image: telegraf:1.15-alpine
#    restart: always
#    environment:
#      USER: bravo
#      INFLUX_URL: influxdb
#      INFLUX_USER: bravo
#      INFLUX_PASSWORD: bravo
#      HOST_PROC: /rootfs/proc
#      HOST_SYS: /rootfs/sys
#      HOST_ETC: /rootfs/etc
#      HOSTNAME: hostname
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
#      - /sys:/rootfs/sys:ro
#      - /proc:/rootfs/proc:ro
#      - /etc:/rootfs/etc:ro
#    networks:
#      - monitoring_availibility_network

networks:
  monitoring_availibility_network:
